# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: bin/project lint
        language: script
        types: [text]
        pass_filenames: false
        always_run: true
        verbose: true
        files: ''

      - id: sync-deps
        name: sync dependencies
        entry: bin/project backend.sync-deps
        language: script
        types: [text]
        pass_filenames: false
        always_run: true
        verbose: true
        files: ''

      # don't want this at all.
      # - id: gen
      #   name: gen
      #   entry: bin/project gen
      #   language: script
      #   types: [text]
      #   pass_filenames: false
      #   always_run: true
      #   verbose: true
      #   files: ''
